[package]
name = "kauri"
version = "0.1.0"
authors = ["Sean Bailey <sean@seanbailey.io>"]
edition = "2018"

[dependencies]
hyper = "0.12"
futures = "0.1.26"
zip = "0.5.2"
xml-rs = "0.8.0"
serde_json = "1.0.39"